import { registerAiReviewIpcHandlers } from './aiReviewIpc';
import { registerCompanionIpcHandlers } from './companionIpc';
import { registerObsidianIpcHandlers } from './obsidianIpc';
import { registerSettingsIpcHandlers } from './settingsIpc';
import { registerTaskContextMenuIpcHandlers, type TaskMenuPayload } from './taskContextMenuIpc';
import { TASK_MENU_HEIGHT } from './taskMenuWindow';
import type {
  MainWindowIpcRegistrationOptions,
  MainWindowIpcRegistrations,
} from './mainWindowIpcRegistrationTypes';
import { registerWindowIpcHandlers } from './windowIpc';

export type { TaskMenuPayload } from './taskContextMenuIpc';
export type {
  MainWindowIpcRegistrationOptions,
  MainWindowIpcRegistrations,
} from './mainWindowIpcRegistrationTypes';

export function createMainWindowIpcRegistrations({
  win,
  store,
  diag,
  scheduleAiTimers,
  getTaskMenuWindow,
  openTaskMenuWindow,
  closeTaskMenuWindow,
  getTaskMenuPayload,
  setTaskMenuPayload,
  getMainWindow,
  getWindowMode,
  hideMainWindow,
  getAppSettings,
  persistWindowState,
  compactModeKey,
  autoStartKey,
  settingsMode,
  setWindowMode,
  setAppSettings,
  reapplyWindowZOrder,
  setInvisibleGlassBackgroundMaterial,
  setNativeWindowDragRegion,
  performanceFrost,
  edgeAutoHide,
  getCompanionSettings,
  setCompanionSettings,
  getAiReviewSettings,
  setAiReviewSettings,
  getObsidianTemplateSettings,
  setObsidianTemplateSettings,
  getReviewSections,
  setReviewSections,
  runReviewForDate,
  inspectDailyAiContent,
  getDateKey,
  getVaultPath,
  getVaultStatus,
  getDailyFilePath,
  buildDailySourceRules,
  getDailySourceRules,
  getLlmCaller,
  ensureReportLlmAvailable,
  emitAiReviewProgress,
  stage,
  createDiagnostic,
  extractDocxText,
  zh,
  obsidianPathKey,
  getDefaultVaultPath,
  syncTasksToObsidian,
  previewTasksToObsidian,
  buildDailyTemplate,
  triggerOverviewUpdate,
}: MainWindowIpcRegistrationOptions): MainWindowIpcRegistrations {
  return {
    registerWindowIpc: () => registerWindowIpcHandlers({
      win,
      store,
      diag,
      compactModeKey,
      autoStartKey,
      settingsMode,
      hideMainWindow,
      getWindowMode,
      setWindowMode,
      persistWindowState,
      getAppSettings,
      setAppSettings,
      getMainWindow,
      reapplyWindowZOrder,
      setInvisibleGlassBackgroundMaterial,
      setNativeWindowDragRegion,
      performanceFrost,
      edgeAutoHide,
    }),
    registerSettingsIpc: () => registerSettingsIpcHandlers({
      store,
      getAppSettings,
      setAppSettings,
      edgeAutoHide,
      getObsidianTemplateSettings,
      setObsidianTemplateSettings,
    }),
    registerTaskContextMenuIpc: () => registerTaskContextMenuIpcHandlers({
      defaultTaskMenuHeight: TASK_MENU_HEIGHT,
      openTaskMenuWindow,
      closeTaskMenuWindow,
      getTaskMenuWindow,
      getMainWindow,
      getTaskMenuPayload,
      setTaskMenuPayload,
    }),
    registerCompanionIpc: () => registerCompanionIpcHandlers({
      getCompanionSettings,
      setCompanionSettings,
    }),
    registerAiReviewIpc: () => registerAiReviewIpcHandlers({
      win,
      getAppSettings,
      getAiReviewSettings,
      setAiReviewSettings,
      getObsidianTemplateSettings,
      getReviewSections,
      setReviewSections,
      scheduleAiTimers,
      runReviewForDate,
      inspectDailyAiContent,
      getDateKey,
      getVaultPath,
      getVaultStatus,
      getDailyFilePath,
      buildDailySourceRules,
      getDailySourceRules,
      getLlmCaller,
      ensureReportLlmAvailable,
      emitAiReviewProgress,
      stage,
      createDiagnostic,
      extractDocxText,
      zh,
    }),
    registerObsidianIpc: () => registerObsidianIpcHandlers({
      win,
      store,
      obsidianPathKey,
      getDefaultVaultPath,
      getVaultPath,
      getVaultStatus,
      getAiReviewSettings,
      getLlmCaller,
      syncTasksToObsidian,
      previewTasksToObsidian,
      getDateKey,
      getDailyFilePath,
      buildDailyTemplate,
      triggerOverviewUpdate,
      zh,
    }),
  };
}
