import type { CreateMainWindowBootstrapOptions } from './mainWindowBootstrap';
import type { SetupMainBrowserWindowOptions } from './mainWindowFactory';

export type MainWindowIpcRegistrationOptions = Pick<
  CreateMainWindowBootstrapOptions,
  | 'win'
  | 'store'
  | 'scheduleAiTimers'
  | 'getTaskMenuWindow'
  | 'openTaskMenuWindow'
  | 'closeTaskMenuWindow'
  | 'getTaskMenuPayload'
  | 'setTaskMenuPayload'
  | 'getMainWindow'
  | 'getWindowMode'
  | 'hideMainWindow'
  | 'getAppSettings'
  | 'persistWindowState'
  | 'compactModeKey'
  | 'autoStartKey'
  | 'settingsMode'
  | 'setWindowMode'
  | 'setAppSettings'
  | 'reapplyWindowZOrder'
  | 'getCompanionSettings'
  | 'setCompanionSettings'
  | 'getAiReviewSettings'
  | 'setAiReviewSettings'
  | 'getObsidianTemplateSettings'
  | 'setObsidianTemplateSettings'
  | 'getReviewSections'
  | 'setReviewSections'
  | 'runReviewForDate'
  | 'inspectDailyAiContent'
  | 'getDateKey'
  | 'getVaultPath'
  | 'getVaultStatus'
  | 'getDailyFilePath'
  | 'buildDailySourceRules'
  | 'getDailySourceRules'
  | 'getLlmCaller'
  | 'ensureReportLlmAvailable'
  | 'emitAiReviewProgress'
  | 'stage'
  | 'createDiagnostic'
  | 'extractDocxText'
  | 'zh'
  | 'obsidianPathKey'
  | 'getDefaultVaultPath'
  | 'syncTasksToObsidian'
  | 'previewTasksToObsidian'
  | 'buildDailyTemplate'
  | 'triggerOverviewUpdate'
>;

export type MainWindowIpcRegistrations = Pick<
  SetupMainBrowserWindowOptions,
  | 'registerWindowIpc'
  | 'registerSettingsIpc'
  | 'registerTaskContextMenuIpc'
  | 'registerCompanionIpc'
  | 'registerAiReviewIpc'
  | 'registerObsidianIpc'
>;
