import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const cleanupCoreCommands = [
  "verify:cleanup-core-runner-module",
  "verify:cleanup-core-runner-exports-module",
  "verify:task-core",
  "verify:task-app-state-actions",
  "verify:task-completion-actions",
  "verify:task-tree-actions",
  "verify:task-ordering-actions",
  "verify:task-persistence-transforms",
  "verify:context-menu",
  "verify:renderer-route",
  "verify:style-entry",
  "verify:app-viewport-style-module",
  "verify:app-task-tree-module",
  "verify:app-task-menu-actions-module",
  "verify:app-task-view-module",
  "verify:app-personalization-module",
  "verify:app-personalization-load-settings",
  "verify:app-theme-state-module",
  "verify:app-review-dialog-state-module",
    "verify:app-ui-state-persistence-module",
  "verify:app-ui-state-persistence-snapshot",
  "verify:app-ui-state-load-snapshot",
  "verify:app-startup-settings-module",
  "verify:app-runtime-effects-module",
  "verify:app-ui-actions-module",
  "verify:app-daily-panel-presentation-module",
  "verify:daily-work-panel-commands-hook",
  "verify:daily-work-panel-resize-hook",
  "verify:markdown-editor-history",
  "verify:openai-client",
  "verify:llm-provider-text-values",
  "verify:companion-capture-item-builder",
  "verify:obsidian-template-task-visibility",
  "verify:llm-client-error-messages",
  "verify:section-config-default-templates",
  "verify:priority-picker-popover-hook",
  "verify:task-completion-dialog-form-hook",
  "verify:task-completion-dialog-markdown-field",
  "verify:header-completion-celebration-hook",
  "verify:title-bar-more-menu-hook",
  "verify:title-bar-primary-actions-module",
  "verify:app-shell-presentation-module",
  "verify:app-shell-composition-types",
  "verify:app-shell-composition-module",
  "verify:app-overlay-stack-module",
  "verify:app-top-content-module",
  "verify:app-main-content-module",
  "verify:app-modal-actions-module",
  "verify:app-shell-effects-module",
  "verify:app-completion-flow-module",
  "verify:app-completion-actions-module",
  "verify:app-scheduled-reports-module",
  "verify:app-ai-review-lifecycle-module",
  "verify:app-companion-status-module",
  "verify:app-companion-capture-module",
  "verify:app-companion-mobile-module",
  "verify:app-companion-actions-module",
  "verify:app-keyboard-shortcuts-module",
  "verify:app-template-editor-module",
  "verify:app-obsidian-template-actions-module",
  "verify:task-list-dnd-module",
  "verify:task-item-context-menu-helper",
  "verify:task-item-virtual-subtasks-hook",
  "verify:task-item-subtasks-viewport",
  "verify:task-item-subtask-card-module",
  "verify:task-item-action-controls-module",
  "verify:task-item-stack-helper",
  "verify:task-item-interactions-helper",
  "verify:task-item-editing-helper",
  "verify:date-key-reuse",
  "verify:date-navigator-module",
  "verify:electron-main-modules",
  "verify:electron-main-store-keys-module",
  "verify:electron-window-state-module",
  "verify:electron-main-window-persistence-module",
  "verify:electron-main-window-composition-module",
  "verify:electron-main-window-startup-module",
  "verify:electron-settings-mode-state-module",
  "verify:electron-user-hidden-state-module",
  "verify:electron-task-date-helpers-module",
  "verify:electron-renderer-loader-module",
  "verify:electron-main-window-mode-controller-module",
  "verify:electron-tray-refresh-bridge-module",
  "verify:electron-window-mode-state-module",
  "verify:electron-main-runtime-state-module",
  "verify:electron-main-localization-module",
  "verify:electron-foundation-modules",
  "verify:electron-diagnostics-safe-start-module",
  "verify:electron-main-diagnostics-bootstrap-module",
  "verify:electron-app-environment-module",
  "verify:electron-native-occlusion-policy-module",
  "verify:electron-single-instance-module",
  "verify:electron-shared-types-module",
  "verify:electron-main-dead-task-alias-cleanup",
  "verify:electron-app-state-accessors-module",
  "verify:legacy-task-export-path-cleanup",
  "verify:electron-win32-native-module",
  "verify:electron-main-window-factory-module",
  "verify:electron-main-window-bootstrap-module",
  "verify:electron-app-lifecycle-module",
  "verify:electron-app-quit-state-module",
  "verify:electron-desktop-window-mode-module",
  "verify:electron-desktop-widget-state-applier-module",
  "verify:electron-main-shell-controller-module",
  "verify:electron-window-ipc-module",
  "verify:electron-settings-ipc-module",
  "verify:electron-task-context-menu-ipc-module",
  "verify:electron-task-menu-window-module",
  "verify:electron-tray-menu-module",
  "verify:electron-main-window-events-module",
  "verify:electron-companion-ipc-module",
  "verify:electron-ai-review-ipc-module",
  "verify:electron-ai-review-ipc-helpers-module",
  "verify:electron-ai-review-ipc-messages-module",
  "verify:electron-ai-review-ipc-month-range-reuse",
  "verify:electron-ai-review-template-tools-ipc-module",
  "verify:electron-ai-review-source-materials-ipc-module",
  "verify:electron-ai-review-backfill-ipc-module",
  "verify:electron-ai-review-external-report-ipc-module",
  "verify:electron-ai-review-weekly-report-ipc-module",
  "verify:electron-ai-review-monthly-report-ipc-module",
  "verify:electron-ai-review-settings-sections-ipc-module",
  "verify:electron-ai-review-daily-run-inspect-ipc-module",
  "verify:electron-ai-review-report-ipc-types-module",
  "verify:electron-ai-review-ipc-registration-types-module",
  "verify:electron-ai-review-report-ipc-diagnostics-module",
  "verify:electron-ai-review-report-ipc-source-summary-module",
  "verify:electron-ai-review-report-ipc-llm-progress-module",
  "verify:electron-ai-review-report-ipc-failure-module",
  "verify:electron-ai-review-report-ipc-completion-module",
  "verify:electron-ai-review-report-ipc-prepare-progress-module",
  "verify:electron-ai-review-report-ipc-preflight-module",
  "verify:electron-ai-review-report-ipc-no-source-failure-module",
  "verify:electron-ai-review-report-ipc-source-collection-module",
  "verify:electron-ai-review-report-ipc-source-preparation-module",
  "verify:electron-ai-review-report-ipc-execution-module",
  "verify:electron-main-ai-review-services-module",
  "verify:electron-ai-review-runtime-module",
  "verify:electron-ai-review-diagnostics-module",
  "verify:electron-ai-review-template-report-generation",
  "verify:electron-ai-review-block-filling",
  "verify:electron-ai-review-daily-progress",
    "verify:electron-ai-review-daily-runner-module",
    "verify:electron-ai-review-daily-content-inspection",
  "verify:electron-ai-review-runner-bridge-module",
  "verify:electron-ai-review-timer-module",
  "verify:electron-obsidian-ipc-module",
  "verify:electron-obsidian-daily-note-content-module",
  "verify:electron-obsidian-sync-module",
  "verify:electron-obsidian-vault-accessors",
  "verify:electron-obsidian-overview-update",
  "verify:electron-obsidian-managed-block-sync",
  "verify:electron-obsidian-sync-preview-module",
  "verify:electron-obsidian-sync-blog-draft-output",
  "verify:electron-obsidian-blog-draft-module",
  "verify:electron-obsidian-companion-template-rules",
  "verify:settings-ai-review-generation-presentation",
  "verify:settings-panel-modules",
  "verify:settings-appearance-module",
  "verify:settings-appearance-section",
  "verify:settings-ai-review-module",
  "verify:settings-ai-review-section",
  "verify:settings-ai-review-report-routing-section",
  "verify:settings-ai-review-source-section",
  "verify:settings-ai-review-manual-generation-section",
  "verify:settings-ai-review-timer-section",
  "verify:settings-basic-sections",
  "verify:settings-sync-section",
  "verify:obsidian-companion-rules-section",
  "verify:obsidian-companion-templates-section",
  "verify:obsidian-template-modules-section",
  "verify:i18n-shell-text-module",
  "typecheck"
];

export function runCleanupCore(): void {
  const npmCli = process.env.npm_execpath;

  if (!npmCli) {
    console.error('Unable to locate npm CLI from npm_execpath. Run this script through npm/tsx via package scripts.');
    process.exit(1);
  }

  for (const command of cleanupCoreCommands) {
    const result = spawnSync(process.execPath, [npmCli, 'run', command], {
      stdio: 'inherit',
      shell: false,
    });

    if (result.status !== 0) {
      process.exit(result.status ?? 1);
    }
  }
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  runCleanupCore();
}
