import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const subtaskCardPath = join(root, 'src/components/taskItem/SubtaskCard.tsx');
const subtaskPresentationPath = join(root, 'src/components/taskItem/subtaskCardPresentation.ts');
const subtaskControlsPath = join(root, 'src/components/taskItem/subtaskCardControls.tsx');
const subtasksViewportPath = join(root, 'src/components/taskItem/TaskSubtasksViewport.tsx');
const iconsPath = join(root, 'src/components/taskItem/taskItemIcons.tsx');
const presentationPath = join(root, 'src/components/taskItem/taskItemPresentation.tsx');
const taskControlsPath = join(root, 'src/components/taskItem/taskItemControls.tsx');
const taskActionControlsPath = join(root, 'src/components/taskItem/taskItemActionControls.tsx');
const taskItemPath = join(root, 'src/components/TaskItem.tsx');
const priorityPickerPath = join(root, 'src/components/PriorityPicker.tsx');
const priorityPickerPopoverPath = join(root, 'src/components/priorityPicker/usePriorityPickerPopover.ts');

assert.ok(existsSync(subtaskCardPath), 'TaskItem subtask card component module should exist.');
assert.ok(existsSync(subtaskPresentationPath), 'TaskItem subtask card presentation helper module should exist.');
assert.ok(existsSync(subtaskControlsPath), 'TaskItem subtask card controls module should exist.');
assert.ok(existsSync(subtasksViewportPath), 'TaskItem subtasks viewport component module should exist.');
assert.ok(existsSync(iconsPath), 'TaskItem SVG icon module should exist.');
assert.ok(existsSync(presentationPath), 'TaskItem shared presentation module should exist.');
assert.ok(existsSync(taskControlsPath), 'TaskItem parent controls module should exist.');
assert.ok(existsSync(taskActionControlsPath), 'TaskItem parent action controls module should exist.');
assert.ok(existsSync(priorityPickerPath), 'PriorityPicker component module should exist.');
assert.ok(existsSync(priorityPickerPopoverPath), 'PriorityPicker popover lifecycle hook should exist.');

const subtaskCard = readFileSync(subtaskCardPath, 'utf8');
const subtaskPresentation = readFileSync(subtaskPresentationPath, 'utf8');
const subtaskControls = readFileSync(subtaskControlsPath, 'utf8');
const subtasksViewport = readFileSync(subtasksViewportPath, 'utf8');
const icons = readFileSync(iconsPath, 'utf8');
const presentation = readFileSync(presentationPath, 'utf8');
const taskControls = readFileSync(taskControlsPath, 'utf8');
const taskActionControls = readFileSync(taskActionControlsPath, 'utf8');
const taskItem = readFileSync(taskItemPath, 'utf8');
const priorityPicker = readFileSync(priorityPickerPath, 'utf8');
const priorityPickerPopover = readFileSync(priorityPickerPopoverPath, 'utf8');

assert.match(subtaskCard, /export interface SubtaskCardProps\b/, 'SubtaskCard module should export its props.');
assert.match(subtaskCard, /export function SubtaskCard\b/, 'SubtaskCard module should export SubtaskCard.');
assert.match(subtaskCard, /from '\.\/taskItemPresentation'/, 'SubtaskCard should reuse shared task-item presentation helpers.');
assert.match(subtaskCard, /from '\.\/subtaskCardPresentation'/, 'SubtaskCard should import subtask presentation helpers.');
assert.match(subtaskCard, /from '\.\/subtaskCardControls'/, 'SubtaskCard should import fixed subtask controls from the controls module.');
assert.match(subtaskCard, /useEffect\(\(\) => \{\s*setEditText\(subtask\.text\);\s*\}, \[subtask\.text\]\)/s, 'SubtaskCard should keep edit text synchronized with the subtask text.');
assert.match(subtaskCard, /onToggleSubtask\(subtask\.id\)/, 'SubtaskCard should keep subtask toggle behavior.');
assert.match(subtaskCard, /const submittedText = getSubmittedTaskText\(editText\);\s*\r?\n\s*if \(submittedText\) onEditSubtask\(subtask\.id, submittedText\);/, 'SubtaskCard should keep trimmed edit submission behavior through the editing helper.');
assert.match(subtaskCard, /onChangeSubtaskPriority\(subtask\.id, priority\)/, 'SubtaskCard should keep subtask priority changes.');
assert.match(subtaskCard, /onViewSubtaskReview\(subtask\)/, 'SubtaskCard should keep subtask review routing.');
assert.match(subtaskCard, /onDeleteSubtask\(subtask\.id\)/, 'SubtaskCard should keep subtask delete routing.');
assert.match(subtaskCard, /className=\{getSubtaskRowClassName\(subtask\.completed\)\}/, 'SubtaskCard should use getSubtaskRowClassName for subtask row classes.');
assert.match(subtaskCard, /<SubtaskCompleteButton\s+completed=\{subtask\.completed\}\s+onClick=\{\(\) => onToggleSubtask\(subtask\.id\)\}/, 'SubtaskCard should render SubtaskCompleteButton for completion routing.');
assert.match(subtaskCard, /<SubtaskPriorityPicker\s+value=\{subtask\.priority\}\s+onChange=\{\(priority\) => onChangeSubtaskPriority\(subtask\.id, priority\)\}/, 'SubtaskCard should render SubtaskPriorityPicker for priority changes.');
assert.match(subtaskCard, /<SubtaskEditInput\s+value=\{editText\}\s+onChange=\{setEditText\}\s+onBlur=\{submitEdit\}\s+onKeyDown=\{handleEditKeyDown\}/, 'SubtaskCard should render SubtaskEditInput while keeping edit state local.');
assert.match(subtaskCard, /<SubtaskText\s+subtask=\{subtask\}\s+onStartEdit=\{\(\) => !subtask\.completed && setIsEditing\(true\)\}/, 'SubtaskCard should render SubtaskText for non-editing text display.');
assert.match(subtaskCard, /<SubtaskActionLayer\s+canOpenReviewAction=\{canOpenReviewAction\}\s+hasReview=\{hasReview\}\s+reviewActionLabel=\{reviewActionLabel\}\s+onViewReview=\{\(\) => onViewSubtaskReview\(subtask\)\}\s+onDelete=\{\(\) => onDeleteSubtask\(subtask\.id\)\}/, 'SubtaskCard should render SubtaskActionLayer for review/delete routing.');

assert.match(subtaskPresentation, /export function getSubtaskCompleteActionLabel\(completed: boolean\)/, 'subtask presentation helper should export getSubtaskCompleteActionLabel.');
assert.match(subtaskPresentation, /export function getSubtaskRowClassName\(completed: boolean\)/, 'subtask presentation helper should export getSubtaskRowClassName.');
assert.match(subtaskPresentation, /export const SUBTASK_PRIORITY_PICKER_TITLE\b/, 'subtask presentation helper should export the priority picker title.');
assert.match(subtaskPresentation, /export const SUBTASK_EDIT_INPUT_LABEL\b/, 'subtask presentation helper should export the edit input label.');
assert.match(subtaskPresentation, /export function getSubtaskTextTitle\(subtask: Pick<Task, 'text' \| 'priority'>\)/, 'subtask presentation helper should export getSubtaskTextTitle.');
assert.match(subtaskPresentation, /export function getSubtaskReviewActionLabel\(hasReview: boolean\)/, 'subtask presentation helper should export getSubtaskReviewActionLabel.');
assert.match(subtaskPresentation, /export const SUBTASK_DELETE_ACTION_LABEL\b/, 'subtask presentation helper should export the delete action label.');
assert.match(subtaskPresentation, /completed \? '\\u6807\\u8bb0\\u5b50\\u4efb\\u52a1\\u4e3a\\u672a\\u5b8c\\u6210' : '\\u6807\\u8bb0\\u5b50\\u4efb\\u52a1\\u4e3a\\u5b8c\\u6210'/, 'subtask complete label should preserve current accessible copy.');
assert.match(subtaskPresentation, /task-subtask-row task-subtask-card \$\{completed \? 'task-subtask-row-completed' : ''\}/, 'subtask row class helper should preserve row and completed classes.');
assert.match(subtaskPresentation, /SUBTASK_PRIORITY_PICKER_TITLE = '\\u8c03\\u6574\\u5b50\\u4efb\\u52a1\\u4f18\\u5148\\u7ea7'/, 'subtask priority picker title should preserve current copy.');
assert.match(subtaskPresentation, /SUBTASK_EDIT_INPUT_LABEL = '\\u7f16\\u8f91\\u5b50\\u4efb\\u52a1'/, 'subtask edit input label should preserve current accessible copy.');
assert.match(subtaskPresentation, /return `\$\{subtask\.text\} \\u00b7 \$\{priorityTitles\[subtask\.priority\]\}`/, 'subtask text title should preserve text plus priority title formatting.');
assert.match(subtaskPresentation, /hasReview \? '\\u67e5\\u770b\\u5b50\\u4efb\\u52a1\\u5b8c\\u6210\\u60c5\\u51b5' : '\\u8865\\u5199\\u5b50\\u4efb\\u52a1\\u5b8c\\u6210\\u60c5\\u51b5'/, 'subtask review label should preserve current accessible copy.');
assert.match(subtaskPresentation, /SUBTASK_DELETE_ACTION_LABEL = '\\u5220\\u9664\\u5b50\\u4efb\\u52a1'/, 'subtask delete label should preserve current accessible copy.');
assert.match(subtaskPresentation, /from '\.\/taskItemPresentation'/, 'subtask presentation helper should reuse shared priority titles.');

assert.match(subtaskControls, /export interface SubtaskEditInputProps\b/, 'subtask controls module should export SubtaskEditInput props.');
assert.match(subtaskControls, /export function SubtaskCompleteButton\b/, 'subtask controls module should export SubtaskCompleteButton.');
assert.match(subtaskControls, /export function SubtaskPriorityPicker\b/, 'subtask controls module should export SubtaskPriorityPicker.');
assert.match(subtaskControls, /export function SubtaskEditInput\b/, 'subtask controls module should export SubtaskEditInput.');
assert.match(subtaskControls, /export function SubtaskText\b/, 'subtask controls module should export SubtaskText.');
assert.match(subtaskControls, /export function SubtaskReviewButton\b/, 'subtask controls module should export SubtaskReviewButton.');
assert.match(subtaskControls, /export function SubtaskDeleteButton\b/, 'subtask controls module should export SubtaskDeleteButton.');
assert.match(subtaskControls, /export function SubtaskActionLayer\b/, 'subtask controls module should export SubtaskActionLayer.');
assert.match(subtaskControls, /from '\.\.\/PriorityPicker'/, 'subtask controls module should own the PriorityPicker dependency.');
assert.match(subtaskControls, /from '\.\/taskItemIcons'/, 'subtask controls module should import shared SVG icons.');
assert.match(subtaskControls, /from '\.\/subtaskCardPresentation'/, 'subtask controls module should import subtask presentation copy helpers.');
assert.match(subtaskControls, /className=\{`task-complete-action task-subtask-complete \$\{completed \? 'task-complete-action-complete' : ''\}`\}/, 'SubtaskCompleteButton should preserve completion action classes.');
assert.match(subtaskControls, /aria-label=\{getSubtaskCompleteActionLabel\(completed\)\}/, 'SubtaskCompleteButton should use the shared completion label helper.');
assert.match(subtaskControls, /<path d="M2 6L5 9L10 3"/, 'SubtaskCompleteButton should preserve the completed checkmark icon path.');
assert.match(subtaskControls, /<PriorityPicker value=\{value\} onChange=\{onChange\} title=\{SUBTASK_PRIORITY_PICKER_TITLE\}/, 'SubtaskPriorityPicker should preserve the priority picker title.');
assert.doesNotMatch(priorityPicker, /event\.target\s+as\s+Node/, 'PriorityPicker should not cast outside-click event targets directly to Node.');
assert.match(priorityPicker, /usePriorityPickerPopover\(\)/, 'PriorityPicker should compose the focused popover lifecycle hook.');
assert.match(priorityPickerPopover, /event\.target\s+instanceof\s+Node/, 'PriorityPicker popover hook should narrow outside-click targets with instanceof Node before contains checks.');
assert.match(priorityPickerPopover, /const repositionFrameRef = useRef<number \| undefined>\(undefined\);/, 'PriorityPicker popover hook should keep one pending frame for scroll-driven repositioning.');
assert.match(priorityPickerPopover, /if \(repositionFrameRef\.current !== undefined\) return;/, 'PriorityPicker popover hook should coalesce repeated scroll reposition events into one animation frame.');
assert.match(priorityPickerPopover, /repositionFrameRef\.current = window\.requestAnimationFrame\(\(\) => \{[\s\S]*?updatePosition\(\);[\s\S]*?\}\);/, 'PriorityPicker popover hook should reposition after the browser batches layout work for the current frame.');
assert.match(priorityPickerPopover, /if \(previous\.top === next\.top && previous\.left === next\.left\) return previous;/, 'PriorityPicker popover hook should skip a React update when the popover position is unchanged.');
assert.match(priorityPickerPopover, /window\.cancelAnimationFrame\(repositionFrameRef\.current\);/, 'PriorityPicker popover hook should cancel pending reposition work when it closes.');
assert.match(priorityPicker, /if \(priority !== value\) onChange\(priority\);\s*closePopover\(\);/, 'PriorityPicker should close when an option is selected but only propagate a real priority change.');
assert.match(subtaskControls, /className="task-edit-input task-subtask-edit-input"/, 'SubtaskEditInput should preserve subtask edit input classes.');
assert.match(subtaskControls, /onChange=\{\(event\) => onChange\(event\.target\.value\)\}/, 'SubtaskEditInput should pass changed text values to its caller.');
assert.match(subtaskControls, /aria-label=\{SUBTASK_EDIT_INPUT_LABEL\}/, 'SubtaskEditInput should use shared accessible copy.');
assert.match(subtaskControls, /className="task-subtask-text"/, 'SubtaskText should preserve the subtask text class.');
assert.match(subtaskControls, /title=\{getSubtaskTextTitle\(subtask\)\}/, 'SubtaskText should use the shared text title helper.');
assert.match(subtaskControls, /onDoubleClick=\{onStartEdit\}/, 'SubtaskText should expose double-click edit routing through a callback.');
assert.match(subtaskControls, /className="task-subtask-review task-icon-action task-review-action task-review-action-visible"/, 'SubtaskReviewButton should preserve review action classes.');
assert.match(subtaskControls, /<ReviewIcon hasReview=\{hasReview\} \/>/, 'SubtaskReviewButton should render the shared review icon.');
assert.match(subtaskControls, /className="task-subtask-delete task-icon-action task-delete-action"/, 'SubtaskDeleteButton should preserve delete action classes.');
assert.match(subtaskControls, /aria-label=\{SUBTASK_DELETE_ACTION_LABEL\}/, 'SubtaskDeleteButton should use shared delete accessible copy.');
assert.match(subtaskControls, /<TrashIcon \/>/, 'SubtaskDeleteButton should render the shared trash icon.');
assert.match(subtaskControls, /className="task-subtask-action-layer task-action-layer"/, 'SubtaskActionLayer should preserve subtask action-layer classes.');
assert.match(subtaskControls, /className="task-action-slot task-action-slot-review task-subtask-review-zone"/, 'SubtaskActionLayer should preserve subtask review slot classes.');
assert.match(subtaskControls, /className="task-action-slot task-action-slot-delete task-subtask-delete-zone"/, 'SubtaskActionLayer should preserve subtask delete slot classes.');

assert.match(presentation, /export const priorityTitles: Record<Task\['priority'\], string>/, 'presentation module should export priority titles.');
assert.match(presentation, /export function hasTaskReview\b/, 'presentation module should export hasTaskReview.');
assert.match(presentation, /export function getTaskTextTitle\(task: Pick<Task, 'text' \| 'priority'>\)/, 'presentation module should export getTaskTextTitle for parent task text titles.');
assert.match(presentation, /return `\$\{task\.text\} \\u00b7 \$\{priorityTitles\[task\.priority\]\}`/, 'getTaskTextTitle should preserve text plus priority title formatting.');
assert.match(presentation, /export function getTaskCardClassName\(/, 'presentation module should export getTaskCardClassName for parent task card classes.');
assert.match(presentation, /export function getTaskClusterClassName\(/, 'presentation module should export getTaskClusterClassName for parent cluster wrapper classes.');
assert.match(presentation, /export function getTaskCompleteActionClassName\(completed: boolean\)/, 'presentation module should export getTaskCompleteActionClassName for parent completion action classes.');
assert.match(presentation, /export function getTaskCompleteActionLabel\(completed: boolean\)/, 'presentation module should export getTaskCompleteActionLabel for parent completion action accessible copy.');
assert.match(presentation, /export function getTaskReviewActionLabel\(hasReview: boolean\)/, 'presentation module should export getTaskReviewActionLabel for parent review action accessible copy.');
assert.match(presentation, /export const TASK_DRAG_HANDLE_LABEL\b/, 'presentation module should export the parent drag-handle accessible copy.');
assert.match(presentation, /export const TASK_EDIT_INPUT_LABEL\b/, 'presentation module should export the parent edit-input accessible copy.');
assert.match(presentation, /export const TASK_DELETE_ACTION_LABEL\b/, 'presentation module should export the parent delete action accessible copy.');
assert.match(presentation, /export const TASK_SUBTASKS_LABEL\b/, 'presentation module should export the parent subtasks region accessible copy.');
assert.match(presentation, /export function getVisibleTaskTags\(tags: string\[\] \| undefined\)/, 'presentation module should export getVisibleTaskTags for parent tag previews.');
assert.match(presentation, /export function getVisibleScheduledDates\(scheduledDates: string\[\] \| undefined\)/, 'presentation module should export getVisibleScheduledDates for parent scheduled-date previews.');
assert.match(presentation, /task-card task-cluster-main-card group/, 'getTaskCardClassName should preserve base parent task card classes.');
assert.match(presentation, /task-card-has-children.*task-card-no-children/s, 'getTaskCardClassName should preserve child-state task card classes.');
assert.match(presentation, /task-card-has-tags.*task-card-no-tags/s, 'getTaskCardClassName should preserve tag-state task card classes.');
assert.match(presentation, /task-card-has-review-action.*task-card-no-review-action/s, 'getTaskCardClassName should preserve review-action task card classes.');
assert.match(presentation, /task-card-completed/, 'getTaskCardClassName should preserve completed task card class.');
assert.match(presentation, /task-cluster \$\{hasChildren \? 'task-cluster-has-children' : 'task-cluster-no-children'\}/, 'getTaskClusterClassName should preserve child-state cluster wrapper classes.');
assert.match(presentation, /task-cluster-expanded.*task-cluster-collapsed/s, 'getTaskClusterClassName should preserve expansion-state cluster wrapper classes.');
assert.match(presentation, /task-complete-action \$\{completed \? 'task-complete-action-complete' : ''\}/, 'getTaskCompleteActionClassName should preserve completion action classes.');
assert.match(presentation, /completed \? '\\u6807\\u8bb0\\u4e3a\\u672a\\u5b8c\\u6210' : '\\u6807\\u8bb0\\u4e3a\\u5b8c\\u6210'/, 'getTaskCompleteActionLabel should preserve completion action labels.');
assert.match(presentation, /hasReview \? '\\u67e5\\u770b\\u5b8c\\u6210\\u60c5\\u51b5' : '\\u8865\\u5199\\u5b8c\\u6210\\u60c5\\u51b5'/, 'getTaskReviewActionLabel should preserve review action labels.');
assert.match(presentation, /TASK_DRAG_HANDLE_LABEL = '\\u62d6\\u52a8\\u8c03\\u6574\\u4efb\\u52a1\\u987a\\u5e8f'/, 'drag handle label should preserve current accessible copy.');
assert.match(presentation, /TASK_EDIT_INPUT_LABEL = '\\u7f16\\u8f91\\u4efb\\u52a1'/, 'edit input label should preserve current accessible copy.');
assert.match(presentation, /TASK_DELETE_ACTION_LABEL = '\\u5220\\u9664\\u4efb\\u52a1'/, 'delete action label should preserve current accessible copy.');
assert.match(presentation, /TASK_SUBTASKS_LABEL = '\\u5b50\\u4efb\\u52a1'/, 'subtasks region label should preserve current accessible copy.');
assert.match(presentation, /visibleTags: tags\?\.slice\(0, 2\) \?\? \[\]/, 'getVisibleTaskTags should preserve the first-two-tags preview.');
assert.match(presentation, /remainingTagCount: Math\.max\(\(tags\?\.length \?\? 0\) - 2, 0\)/, 'getVisibleTaskTags should preserve remaining tag count behavior.');
assert.match(presentation, /visibleScheduledDates: scheduledDates\?\.slice\(0, 3\) \?\? \[\]/, 'getVisibleScheduledDates should preserve the first-three-dates preview.');
assert.match(presentation, /remainingScheduledDateCount: Math\.max\(\(scheduledDates\?\.length \?\? 0\) - 3, 0\)/, 'getVisibleScheduledDates should preserve remaining scheduled date count behavior.');
assert.match(taskControls, /export interface TaskEditInputProps\b/, 'TaskItem controls module should export TaskEditInput props.');
assert.match(taskControls, /export interface TaskMainContentProps\b/, 'TaskItem controls module should export TaskMainContent props.');
assert.match(taskActionControls, /export function ReviewActionButton\b/, 'TaskItem action controls module should export ReviewActionButton.');
assert.match(taskActionControls, /export function TaskActionLayer\b/, 'TaskItem action controls module should export TaskActionLayer.');
assert.match(taskActionControls, /export function CompleteActionButton\b/, 'TaskItem action controls module should export CompleteActionButton.');
assert.match(taskActionControls, /export function DeleteActionButton\b/, 'TaskItem action controls module should export DeleteActionButton.');
assert.match(taskControls, /export function TaskEditInput\b/, 'TaskItem controls module should export TaskEditInput.');
assert.match(taskControls, /export function TaskMainContent\b/, 'TaskItem controls module should export TaskMainContent.');
assert.match(taskControls, /export interface TaskDragHandleProps\b/, 'TaskItem controls module should export TaskDragHandleProps.');
assert.match(taskControls, /export function DragHandleButton\b/, 'TaskItem controls module should export DragHandleButton.');

assert.match(icons, /export function ReviewIcon\b/, 'icon module should export ReviewIcon.');
assert.match(icons, /export function DragDotsIcon\b/, 'icon module should export DragDotsIcon.');
assert.match(icons, /export function TrashIcon\b/, 'icon module should export TrashIcon.');
assert.match(icons, /M2 12s3\.5-7 10-7 10 7 10 7-3\.5 7-10 7-10-7-10-7z/, 'ReviewIcon should preserve the existing review-eye path.');
assert.match(icons, /M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z/, 'ReviewIcon should preserve the empty-review document path.');
assert.match(icons, /circle cx="3" cy="3" r="1\.15"/, 'DragDotsIcon should preserve the drag-dot circles.');
assert.match(icons, /M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m3 0v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6h14/, 'TrashIcon should preserve the existing trash path.');
assert.match(taskControls, /from '\.\/taskItemIcons'/, 'TaskItem controls module should import its drag icon from the icon module.');
assert.match(taskActionControls, /from '\.\/taskItemIcons'/, 'TaskItem action controls module should import action icons from the icon module.');
assert.match(taskControls, /from '\.\/taskItemPresentation'/, 'TaskItem controls module should import parent presentation helpers.');
assert.match(taskActionControls, /from '\.\/taskItemPresentation'/, 'TaskItem action controls module should import action presentation helpers.');
assert.doesNotMatch(presentation, /export function ReviewIcon\b/, 'presentation module should not define ReviewIcon after extracting icons.');
assert.doesNotMatch(presentation, /export function DragDotsIcon\b/, 'presentation module should not define DragDotsIcon after extracting icons.');
assert.doesNotMatch(presentation, /export function TrashIcon\b/, 'presentation module should not define TrashIcon after extracting icons.');
assert.doesNotMatch(presentation, /export function ReviewActionButton\b/, 'presentation module should not define ReviewActionButton after extracting parent controls.');
assert.doesNotMatch(presentation, /export function TaskActionLayer\b/, 'presentation module should not define TaskActionLayer after extracting parent controls.');
assert.doesNotMatch(presentation, /export function CompleteActionButton\b/, 'presentation module should not define CompleteActionButton after extracting parent controls.');
assert.doesNotMatch(presentation, /export function DeleteActionButton\b/, 'presentation module should not define DeleteActionButton after extracting parent controls.');
assert.doesNotMatch(presentation, /export function TaskEditInput\b/, 'presentation module should not define TaskEditInput after extracting parent controls.');
assert.doesNotMatch(presentation, /export function TaskMainContent\b/, 'presentation module should not define TaskMainContent after extracting parent controls.');
assert.doesNotMatch(presentation, /export function DragHandleButton\b/, 'presentation module should not define DragHandleButton after extracting parent controls.');

assert.match(subtasksViewport, /from '\.\/SubtaskCard'/, 'TaskSubtasksViewport should import the SubtaskCard module.');
assert.match(taskItem, /lazy\(\(\) => import\('\.\/taskItem\/TaskSubtasksViewport'\)/, 'TaskItem should lazy-load the TaskSubtasksViewport module.');
assert.doesNotMatch(taskItem, /import \{ TaskSubtasksViewport \} from '\.\/taskItem\/TaskSubtasksViewport'/, 'TaskItem should not statically import the TaskSubtasksViewport module.');
assert.match(taskItem, /from '\.\/taskItem\/taskItemPresentation'/, 'TaskItem should import shared presentation helpers.');
assert.match(taskItem, /from '\.\/taskItem\/taskItemControls'/, 'TaskItem should import parent task controls from the controls module.');
assert.match(taskItem, /from '\.\/taskItem\/taskItemActionControls'/, 'TaskItem should import parent task actions from the action controls module.');
assert.match(subtasksViewport, /<SubtaskCard\b/, 'TaskSubtasksViewport should render SubtaskCard for visible virtual subtask items.');
assert.match(taskItem, /<TaskSubtasksViewport\b/, 'TaskItem should render TaskSubtasksViewport for expanded subtask rendering.');
assert.match(taskControls, /title=\{getTaskTextTitle\(task\)\}/, 'TaskMainContent should use getTaskTextTitle for the parent text title.');
assert.match(taskItem, /className=\{getTaskCardClassName\(\{\s*hasChildren,\s*hasTags,\s*canOpenReviewAction,\s*completed: task\.completed,\s*\}\)\}/s, 'TaskItem should use getTaskCardClassName for parent task card classes.');
assert.match(taskItem, /className=\{getTaskClusterClassName\(\{\s*hasChildren,\s*isExpanded,\s*\}\)\}/s, 'TaskItem should use getTaskClusterClassName for parent cluster wrapper classes.');
assert.match(taskItem, /const completeActionLabel = getTaskCompleteActionLabel\(task\.completed\);/, 'TaskItem should use getTaskCompleteActionLabel for parent completion action accessible copy.');
assert.match(taskItem, /const reviewActionLabel = getTaskReviewActionLabel\(hasReview\);/, 'TaskItem should use getTaskReviewActionLabel for parent review action accessible copy.');
assert.match(taskControls, /aria-label=\{TASK_DRAG_HANDLE_LABEL\}/, 'DragHandleButton should use shared accessible copy for the drag handle.');
assert.match(taskControls, /aria-label=\{TASK_EDIT_INPUT_LABEL\}/, 'TaskEditInput should use shared accessible copy for the edit input.');
assert.match(taskControls, /className="task-edit-input"/, 'TaskEditInput should preserve the edit input class.');
assert.match(taskControls, /onChange=\{\(event\) => onChange\(event\.target\.value\)\}/, 'TaskEditInput should pass changed text values to its caller.');
assert.match(taskControls, /autoFocus/, 'TaskEditInput should preserve autofocus behavior.');
assert.match(taskControls, /onClick=\{\(event\) => event\.stopPropagation\(\)\}/, 'TaskEditInput should preserve click propagation blocking.');
assert.match(taskControls, /onPointerDown=\{\(event\) => event\.stopPropagation\(\)\}/, 'TaskEditInput should preserve pointer propagation blocking.');
assert.match(taskControls, /<TaskEditInput\s+value=\{editText\}\s+onChange=\{onEditTextChange\}\s+onBlur=\{onSubmitEdit\}\s+onKeyDown=\{onEditKeyDown\}/, 'TaskMainContent should render TaskEditInput while delegating edit state and handlers.');
assert.match(taskControls, /className="task-text-wrap"/, 'TaskMainContent should preserve the parent text wrapper class.');
assert.match(taskControls, /className="task-text-row"/, 'TaskMainContent should preserve the parent text row class.');
assert.match(taskControls, /className="task-text"/, 'TaskMainContent should preserve the parent task text class.');
assert.match(taskControls, /title=\{getTaskTextTitle\(task\)\}/, 'TaskMainContent should own parent text title formatting.');
assert.match(taskControls, /onDoubleClick=\{onStartEdit\}/, 'TaskMainContent should expose double-click edit routing through a callback.');
assert.match(taskControls, /className="task-tags task-inline-tags"/, 'TaskMainContent should preserve parent tag preview classes.');
assert.match(taskControls, /visibleTags\.map\(\(tag\) =>/, 'TaskMainContent should render visible tag previews.');
assert.match(taskControls, /className="scheduled-dates"/, 'TaskMainContent should preserve scheduled date preview class.');
assert.match(taskControls, /visibleScheduledDates\.join\('/, 'TaskMainContent should render visible scheduled-date previews with the existing join separator.');
assert.match(taskActionControls, /aria-label=\{TASK_DELETE_ACTION_LABEL\}/, 'DeleteActionButton should use shared accessible copy for the delete action aria-label.');
assert.match(taskActionControls, /title=\{TASK_DELETE_ACTION_LABEL\}/, 'DeleteActionButton should use shared accessible copy for the delete action title.');
assert.match(taskActionControls, /className="task-action-layer"/, 'TaskActionLayer should preserve the parent action layer class.');
assert.match(taskActionControls, /className="task-action-slot task-action-slot-review task-review-zone"/, 'TaskActionLayer should preserve the parent review action slot classes.');
assert.match(taskActionControls, /className="task-action-slot task-action-slot-delete task-delete-zone"/, 'TaskActionLayer should preserve the parent delete action slot classes.');
assert.match(taskActionControls, /aria-hidden=\{false\}/, 'TaskActionLayer should preserve the visible action layer accessibility setting.');
assert.match(taskActionControls, /onClick=\{\(event\) => event\.stopPropagation\(\)\}/, 'TaskActionLayer should preserve click propagation blocking.');
assert.match(taskActionControls, /onPointerDown=\{\(event\) => event\.stopPropagation\(\)\}/, 'TaskActionLayer should preserve pointer propagation blocking.');
assert.match(subtasksViewport, /aria-label=\{TASK_SUBTASKS_LABEL\}/, 'TaskSubtasksViewport should use shared accessible copy for the subtasks region.');
assert.match(taskActionControls, /className=\{getTaskCompleteActionClassName\(completed\)\}/, 'CompleteActionButton should use getTaskCompleteActionClassName for parent completion action classes.');
assert.match(taskActionControls, /aria-label=\{label\}/, 'CompleteActionButton should reuse the provided completion action label for aria-label.');
assert.match(taskActionControls, /title=\{label\}/, 'CompleteActionButton should reuse the provided completion action label for title.');
assert.match(taskActionControls, /event\.stopPropagation\(\);\s*onClick\(\);/s, 'CompleteActionButton should preserve click propagation blocking before toggling completion.');
assert.match(taskActionControls, /onPointerDown=\{\(event\) => event\.stopPropagation\(\)\}/, 'CompleteActionButton should preserve pointer propagation blocking.');
assert.match(taskActionControls, /<path d="M2 6L5 9L10 3"/, 'CompleteActionButton should preserve the completed checkmark icon path.');
assert.match(taskItem, /reviewActionLabel=\{reviewActionLabel\}/, 'TaskItem should pass the derived review action label into TaskActionLayer.');
assert.match(taskItem, /<CompleteActionButton\s+completed=\{task\.completed\}\s+label=\{completeActionLabel\}\s+onClick=\{onToggle\}/, 'TaskItem should render CompleteActionButton for the parent completion action.');
assert.match(taskItem, /<TaskActionLayer\s+canOpenReviewAction=\{canOpenReviewAction\}\s+hasReview=\{hasReview\}\s+reviewActionLabel=\{reviewActionLabel\}\s+onViewReview=\{onViewReview\}\s+onDelete=\{onDelete\}/, 'TaskItem should render TaskActionLayer for the parent review/delete actions.');
assert.match(taskItem, /<DragHandleButton\s+dragHandleProps=\{dragHandleProps\}/, 'TaskItem should render DragHandleButton for the parent drag handle.');
assert.match(taskItem, /<TaskMainContent\s+task=\{task\}\s+isEditing=\{isEditing\}\s+editText=\{editText\}\s+visibleTags=\{visibleTags\}\s+remainingTagCount=\{remainingTagCount\}\s+visibleScheduledDates=\{visibleScheduledDates\}\s+remainingScheduledDateCount=\{remainingScheduledDateCount\}/s, 'TaskItem should render TaskMainContent for parent edit/text/metadata markup.');
assert.match(taskItem, /export type \{ TaskDragHandleProps \} from '\.\/taskItem\/taskItemControls';/, 'TaskItem should keep re-exporting TaskDragHandleProps for external consumers.');
assert.match(taskItem, /const \{ visibleTags, remainingTagCount \} = getVisibleTaskTags\(task\.tags\);/, 'TaskItem should use getVisibleTaskTags for parent tag preview data.');
assert.match(taskItem, /const \{ visibleScheduledDates, remainingScheduledDateCount \} = getVisibleScheduledDates\(task\.scheduledDates\);/, 'TaskItem should use getVisibleScheduledDates for parent scheduled-date preview data.');
assert.doesNotMatch(taskItem, /function SubtaskCard\b/, 'TaskItem should not inline SubtaskCard.');
assert.doesNotMatch(taskItem, /function ReviewIcon\b/, 'TaskItem should not inline ReviewIcon.');
assert.doesNotMatch(taskItem, /function TrashIcon\b/, 'TaskItem should not inline TrashIcon.');
assert.doesNotMatch(taskItem, /function DragDotsIcon\b/, 'TaskItem should not inline DragDotsIcon.');
assert.doesNotMatch(taskItem, /function hasTaskReview\b/, 'TaskItem should not inline hasTaskReview.');
assert.doesNotMatch(taskItem, /priorityTitles\[task\.priority\]/, 'TaskItem should not inline parent text title formatting.');
assert.doesNotMatch(taskItem, /task-card-has-children.*task-card-no-children/s, 'TaskItem should not inline parent task card class composition.');
assert.doesNotMatch(taskItem, /task-cluster-has-children.*task-cluster-no-children/s, 'TaskItem should not inline parent cluster wrapper class composition.');
assert.doesNotMatch(taskItem, /task-complete-action \$\{task\.completed \? 'task-complete-action-complete' : ''\}/, 'TaskItem should not inline parent completion action class composition.');
assert.doesNotMatch(taskItem, /className=\{getTaskCompleteActionClassName\(task\.completed\)\}/, 'TaskItem should not wire completion action classes directly after extracting CompleteActionButton.');
assert.doesNotMatch(taskItem, /aria-label=\{task\.completed \?/, 'TaskItem should not inline parent completion action aria-label ternary.');
assert.doesNotMatch(taskItem, /title=\{task\.completed \?/, 'TaskItem should not inline parent completion action title ternary.');
assert.doesNotMatch(taskItem, /<path d="M2 6L5 9L10 3"/, 'TaskItem should not inline the parent completion checkmark icon.');
assert.doesNotMatch(taskItem, /label=\{hasReview \?/, 'TaskItem should not inline parent review action label ternary.');
assert.doesNotMatch(taskItem, /aria-label="拖动调整任务顺序"/, 'TaskItem should not inline drag handle accessible copy.');
assert.doesNotMatch(taskItem, /aria-label="编辑任务"/, 'TaskItem should not inline edit input accessible copy.');
assert.doesNotMatch(taskItem, /aria-label="删除任务"/, 'TaskItem should not inline delete action accessible copy.');
assert.doesNotMatch(taskItem, /title="删除任务"/, 'TaskItem should not inline delete action title copy.');
assert.doesNotMatch(taskItem, /aria-label="子任务"/, 'TaskItem should not inline subtasks region accessible copy.');
assert.doesNotMatch(taskItem, /className="task-icon-action task-delete-action"/, 'TaskItem should not inline parent delete action markup.');
assert.doesNotMatch(taskItem, /className="task-action-layer"/, 'TaskItem should not inline parent action layer markup.');
assert.doesNotMatch(taskItem, /className="task-action-slot task-action-slot-review task-review-zone"/, 'TaskItem should not inline parent review action slot markup.');
assert.doesNotMatch(taskItem, /className="task-action-slot task-action-slot-delete task-delete-zone"/, 'TaskItem should not inline parent delete action slot markup.');
assert.doesNotMatch(taskItem, /className="task-drag-handle"/, 'TaskItem should not inline parent drag handle markup.');
assert.doesNotMatch(taskItem, /className="task-edit-input"/, 'TaskItem should not inline parent edit input markup.');
assert.doesNotMatch(taskItem, /<TaskEditInput\b/, 'TaskItem should not render TaskEditInput directly after extracting TaskMainContent.');
assert.doesNotMatch(taskItem, /className="task-text-wrap"/, 'TaskItem should not inline parent text wrapper markup.');
assert.doesNotMatch(taskItem, /className="task-tags task-inline-tags"/, 'TaskItem should not inline parent tag preview markup.');
assert.doesNotMatch(taskItem, /className="scheduled-dates"/, 'TaskItem should not inline parent scheduled-date preview markup.');
assert.doesNotMatch(taskItem, /task\.tags\.slice\(0, 2\)/, 'TaskItem should not inline parent tag preview slicing.');
assert.doesNotMatch(taskItem, /task\.scheduledDates\.slice\(0, 3\)/, 'TaskItem should not inline parent scheduled-date preview slicing.');
assert.doesNotMatch(taskItem, /<SubtaskCard\b/, 'TaskItem should not render SubtaskCard directly after extracting TaskSubtasksViewport.');
assert.doesNotMatch(taskItem, /task-subtask-row task-subtask-card/, 'TaskItem should not own subtask row markup.');
assert.doesNotMatch(taskItem, /task-subtask-delete task-icon-action task-delete-action/, 'TaskItem should not own subtask delete action markup.');
assert.doesNotMatch(subtaskCard, /onEditSubtask\(subtask\.id, editText\.trim\(\)\)/, 'SubtaskCard should not inline edit text trimming after adopting the editing helper.');
assert.doesNotMatch(subtaskCard, /subtask\.completed \? '标记子任务为未完成' : '标记子任务为完成'/, 'SubtaskCard should not inline completion action labels.');
assert.doesNotMatch(subtaskCard, /<button[\s\S]*task-subtask-complete/, 'SubtaskCard should not inline subtask completion button markup.');
assert.doesNotMatch(subtaskCard, /<PriorityPicker\b/, 'SubtaskCard should not inline subtask priority picker markup.');
assert.doesNotMatch(subtaskCard, /className="task-edit-input task-subtask-edit-input"/, 'SubtaskCard should not inline subtask edit input markup.');
assert.doesNotMatch(subtaskCard, /task-subtask-row task-subtask-card/, 'SubtaskCard should not inline subtask row class composition.');
assert.doesNotMatch(subtaskCard, /className="task-subtask-text"/, 'SubtaskCard should not inline subtask text markup.');
assert.doesNotMatch(subtaskCard, /className="task-subtask-action-layer task-action-layer"/, 'SubtaskCard should not inline subtask action-layer markup.');
assert.doesNotMatch(subtaskCard, /className="task-subtask-review task-icon-action task-review-action task-review-action-visible"/, 'SubtaskCard should not inline subtask review action markup.');
assert.doesNotMatch(subtaskCard, /className="task-subtask-delete task-icon-action task-delete-action"/, 'SubtaskCard should not inline subtask delete action markup.');
assert.doesNotMatch(subtaskCard, /title="调整子任务优先级"/, 'SubtaskCard should not inline the subtask priority picker title.');
assert.doesNotMatch(subtaskCard, /aria-label="编辑子任务"/, 'SubtaskCard should not inline the subtask edit input label.');
assert.doesNotMatch(subtaskCard, /title=\{`\$\{subtask\.text\} .* \$\{priorityTitles\[subtask\.priority\]\}`\}/, 'SubtaskCard should not inline subtask text title formatting.');
assert.doesNotMatch(subtaskCard, /hasReview \? '查看子任务完成情况' : '补写子任务完成情况'/, 'SubtaskCard should not inline subtask review action labels.');
assert.doesNotMatch(subtaskCard, /aria-label="删除子任务"/, 'SubtaskCard should not inline the subtask delete action aria-label.');
assert.doesNotMatch(subtaskCard, /title="删除子任务"/, 'SubtaskCard should not inline the subtask delete action title.');

console.log('TaskItem SubtaskCard module verification passed');
