import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertCleanupCoreIncludes } from './verifyCleanupCore';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const topContentPath = join(root, 'src/components/AppTopContent.tsx');
const headerPath = join(root, 'src/components/Header.tsx');
const headerCelebrationHookPath = join(root, 'src/components/header/useCompletionCelebration.ts');
const helperPath = join(root, 'src/app/appShellComposition.tsx');
const mainContentCompositionPath = join(root, 'src/app/appShellMainContentComposition.tsx');
const runtimeCompositionPath = join(root, 'src/app/useAppShellComposition.ts');
const appPath = join(root, 'src/App.tsx');
const packagePath = join(root, 'package.json');

assert.ok(existsSync(topContentPath), 'App top content component should exist.');
assert.ok(existsSync(headerPath), 'Header component should exist for celebration loading verification.');
assert.ok(existsSync(headerCelebrationHookPath), 'Header completion celebration hook should exist.');
assert.ok(existsSync(helperPath), 'App shell composition helper should exist for top-content wiring verification.');
assert.ok(existsSync(mainContentCompositionPath), 'App shell main-content composition helper should exist for top-content wiring verification.');

const topContent = readFileSync(topContentPath, 'utf8');
const header = readFileSync(headerPath, 'utf8');
const headerCelebrationHook = readFileSync(headerCelebrationHookPath, 'utf8');
const helper = readFileSync(helperPath, 'utf8');
const mainContentComposition = readFileSync(mainContentCompositionPath, 'utf8');
const runtimeComposition = readFileSync(runtimeCompositionPath, 'utf8');
const app = readFileSync(appPath, 'utf8');
const packageJson = JSON.parse(readFileSync(packagePath, 'utf8'));
const scripts = packageJson.scripts as Record<string, string>;

assert.match(topContent, /export interface AppTopContentProps\b/, 'top content should export AppTopContentProps.');
assert.match(topContent, /export const AppTopContent = memo\(function AppTopContent\(/, 'top content should export AppTopContent.');
assert.match(topContent, /import \{ memo, type ComponentProps \} from 'react';/, 'top content should import memo for semantic top-area render isolation.');
assert.match(topContent, /function areAppTopContentPropsEqual\(/, 'top content should compare recreated shell prop bags by their values.');
assert.match(topContent, /export const AppTopContent = memo\(function AppTopContent\(/, 'top content should memoize the top area across unrelated app updates.');
assert.match(topContent, /\}, areAppTopContentPropsEqual\);/, 'top content memoization should use the semantic props comparator.');
assert.match(topContent, /from '\.\/Header'/, 'top content should own Header import.');
assert.match(topContent, /from '\.\/DateNavigator'/, 'top content should own DateNavigator import.');
assert.doesNotMatch(topContent, /DailyWorkPanel|daily-panels/, 'top content should leave daily editor mounting to the task workspace.');
assert.doesNotMatch(topContent, /TabBar|tabBarProps/, 'top content should not retain a separate task-view tab row.');
assert.match(topContent, /<Header\b/, 'top content should render Header.');
assert.match(topContent, /<DateNavigator\b/, 'top content should render DateNavigator.');
assert.match(topContent, /const calendar = useDateNavigatorCalendar\(headerProps\.selectedDate\);/, 'top content should create one shared calendar controller.');
assert.match(topContent, /className="top-calendar-controller" ref=\{calendar\.calendarRef\}/, 'shared calendar controller should own the click-outside boundary.');
assert.match(topContent, /<Header \{\.\.\.headerProps\} calendar=\{calendar\} text=\{shellText\} \/>/, 'Header should receive the shared calendar controller and localized text.');
assert.match(topContent, /<DateNavigator \{\.\.\.dateNavigatorProps\} calendar=\{calendar\} \/>/, 'DateNavigator should receive the shared calendar controller.');
assert.doesNotMatch(topContent, /daily-panel-switch/, 'top content should not render the permanent daily editor switch.');
assert.doesNotMatch(header, /^import confetti from 'canvas-confetti';$/m, 'Header should not eagerly load canvas-confetti on application startup.');
assert.match(header, /from '\.\/header\/useCompletionCelebration'/, 'Header should delegate celebration lifecycle to its focused hook.');
assert.match(header, /useCompletionCelebration\(\{ completedCount, totalCount \}\);/, 'Header should pass current completion counts to its celebration hook.');
assert.match(headerCelebrationHook, /void import\('canvas-confetti'\)\.then\(\(\{ default: confetti \}\) => \{/, 'Header celebration hook should load canvas-confetti only when all tasks become complete.');
assert.match(headerCelebrationHook, /confetti\(\{[\s\S]*particleCount: 90,[\s\S]*\}\);/, 'Header celebration hook should preserve the existing completion celebration payload.');
assert.match(header, /import \{ memo \} from 'react';/, 'Header should import memo to isolate stable header props from unrelated task updates.');
assert.match(header, /export const Header = memo\(function Header\(/, 'Header should memoize its stable summary surface.');
assert.doesNotMatch(header, /dateContextLabel|formattedDateLabel|header-progress-row/, 'Header should not render date context or header progress.');
assert.match(header, /onClick=\{calendar\.toggleCalendar\}/, 'Header calendar action should control the shared calendar.');

assert.match(mainContentComposition, /from '\.\.\/components\/AppTopContent'/, 'main-content composition helper should import AppTopContent.');
assert.match(mainContentComposition, /const topContentProps = \{[\s\S]*headerProps,[\s\S]*dateNavigatorProps,[\s\S]*shellText:\s*shellText\.app,[\s\S]*\};/, 'main-content composition helper should gather top content props without a separate tab-bar boundary.');
assert.doesNotMatch(mainContentComposition, /tabBarProps/, 'main-content composition should not recreate the removed tab-bar prop bag.');
assert.match(mainContentComposition, /const taskListProps = \{[\s\S]*activeTab,[\s\S]*onTabChange: setActiveTab,[\s\S]*selectedDateTasksForCommands,[\s\S]*onCloseDailyWorkPanel: appUiActions\.closeDailyWorkPanel,[\s\S]*onCloseInspirationPanel: appUiActions\.closeInspirationPanel,[\s\S]*\};/, 'main-content composition helper should hand view selection and daily editor data to the task workspace.');
assert.match(mainContentComposition, /topContent:\s*<AppTopContent \{\.\.\.topContentProps\} \/>/, 'main-content composition helper should delegate top-area rendering into AppTopContent.');
assert.match(helper, /const mainContentProps = createAppShellMainContentComposition\(mainContent\);/, 'outer shell composition should delegate the grouped main-content input unchanged.');

assert.match(app, /from '\.\/app\/useAppShellComposition'/, 'App should import the runtime shell composition hook.');
assert.match(app, /const shellComposition = useAppShellComposition\(\{/, 'App should build shell composition through the runtime hook.');
assert.match(runtimeComposition, /from '\.\/appShellComposition'/, 'runtime shell composition hook should import the shell composition helper.');
assert.match(runtimeComposition, /return createAppShellComposition\(createAppShellCompositionInputs\(\{/, 'runtime shell composition hook should delegate to the shell composition helper through pure inputs.');
assert.match(app, /<AppMainContent \{\.\.\.shellComposition\.mainContentProps\} \/>/, 'App should delegate main content rendering through shell composition.');
assert.doesNotMatch(app, /from '\.\/components\/AppTopContent'/, 'App should no longer import AppTopContent directly once shell composition owns it.');
assert.doesNotMatch(app, /const topContentProps = \{/, 'App should not inline top content prop assembly once shell composition owns it.');
assert.doesNotMatch(app, /<AppTopContent\b/, 'App should not render AppTopContent directly once shell composition owns it.');
assert.doesNotMatch(app, /<Header\b/, 'App should not render Header directly once AppTopContent owns the top area.');
assert.doesNotMatch(app, /<DateNavigator\b/, 'App should not render DateNavigator directly once AppTopContent owns the top area.');
assert.doesNotMatch(app, /<DailyWorkPanel\b/, 'App should not render DailyWorkPanel directly once AppTopContent owns the top area.');
assert.doesNotMatch(app, /<TabBar\b/, 'App should not render TabBar directly once AppTopContent owns the top area.');
assert.equal(scripts['verify:app-top-content-module'], 'tsx scripts/verify-app-top-content-module.ts', 'package.json should expose the focused App top-content verifier.');
assertCleanupCoreIncludes('verify:app-top-content-module', 'cleanup-core should include the focused App top-content verifier.');

console.log('App top content verification passed');
