import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const taskItem = readFileSync(join(root, 'src/components/TaskItem.tsx'), 'utf8');
const taskItemControls = readFileSync(join(root, 'src/components/taskItem/taskItemControls.tsx'), 'utf8');
const taskItemActionControls = readFileSync(join(root, 'src/components/taskItem/taskItemActionControls.tsx'), 'utf8');
const subtaskCard = readFileSync(join(root, 'src/components/taskItem/SubtaskCard.tsx'), 'utf8');
const subtaskCardControls = readFileSync(join(root, 'src/components/taskItem/subtaskCardControls.tsx'), 'utf8');
const globals = readFileSync(join(root, 'src/styles/globals.css'), 'utf8').replace(/\r\n/g, '\n');
const watercolor = readFileSync(join(root, 'src/styles/watercolor-theme.css'), 'utf8').replace(/\r\n/g, '\n');

assert.ok(taskItem.includes('<TaskActionLayer'), 'Main task rows should render the extracted action layer.');
assert.ok(taskItemActionControls.includes('task-action-slot task-action-slot-review'), 'Main task review action should use action slot class.');
assert.ok(taskItemActionControls.includes('task-action-slot task-action-slot-delete'), 'Main task delete action should use action slot class.');
assert.ok(subtaskCard.includes('<SubtaskActionLayer'), 'Subtask rows should render the extracted subtask action layer.');
assert.ok(subtaskCardControls.includes('task-subtask-action-layer task-action-layer'), 'Subtask action layer should reuse shared action layer class.');
assert.ok(subtaskCardControls.includes('task-subtask-review task-icon-action task-review-action'), 'Subtask review should reuse shared review button class.');
assert.ok(subtaskCardControls.includes('task-subtask-delete task-icon-action task-delete-action'), 'Subtask delete should reuse shared delete button class.');
assert.ok(globals.includes('.task-action-layer {\n  display: grid !important;'), 'Shared task action layer should have final important grid rules to beat older compact overrides.');
assert.ok(globals.includes('grid-template-columns: var(--task-review-action-width) var(--task-delete-action-width) !important;'), 'Task action grid should reserve review/delete columns with final specificity.');
assert.ok(globals.includes('width: calc(var(--task-review-action-width) + var(--task-delete-action-width) + var(--task-action-gap)) !important;'), 'Main and subtask action layers should share the same important fixed width.');
assert.ok(globals.includes('grid-template-columns: var(--task-review-action-width) var(--task-delete-action-width) !important;'), 'Main and subtask action layers should share the same important review/delete columns.');
assert.ok(globals.includes('gap: var(--task-action-gap) !important;'), 'Main and subtask action layers should share the same important action gap.');
assert.ok(globals.includes('--task-action-right: 0.62rem;'), 'Main/subtask action layers should share the main task right column offset.');
assert.ok(globals.includes('--task-action-safe-space: 4.85rem;'), 'Main task should define the shared trailing safe space for the action column.');
assert.match(globals, /\.task-subtask-row \{[\s\S]*?padding-right: var\(--task-action-safe-space\) !important;/, 'Subtask row should reserve the same trailing safe space as the main task action column.');
assert.ok(globals.includes('right: var(--task-action-right) !important;'), 'Task action layers should use the shared right offset variable.');
assert.ok(!globals.includes('right: 0.1rem !important;'), 'Subtask actions should not keep a separate right offset from main task actions.');
assert.ok(globals.includes('.task-subtask-action-layer.task-action-layer {\n  position: absolute !important;\n  right: var(--task-action-right) !important;'), 'Subtask action layer should align to the same right column as main tasks.');
assert.ok(globals.includes('inset-block: 0 !important;'), 'Subtask action layer should span the full row height for vertical centering.');
assert.ok(globals.includes('top: 0 !important;'), 'Subtask action layer should not rely on 50% top positioning for row centering.');
assert.ok(globals.includes('transform: none !important;'), 'Subtask action layer should not use translateY for vertical centering.');
assert.ok(globals.includes('align-content: center !important;'), 'Subtask action layer grid should center slots within the full row height.');
assert.ok(globals.includes('justify-content: end !important;'), 'Subtask action layer should preserve main-task right-column alignment while vertically centering.');
assert.ok(globals.includes('grid-template-columns: var(--task-review-action-width) var(--task-delete-action-width) !important;'), 'Subtask action layer should use the same review/delete columns as main tasks.');
assert.ok(globals.includes('min-width: calc(var(--task-review-action-width) + var(--task-delete-action-width) + var(--task-action-gap)) !important;'), 'Subtask action layer should reserve the same action grid width as main tasks.');
assert.ok(!globals.includes('place-content: center !important;'), 'Subtask action layer should not center the whole action grid horizontally away from the main task columns.');
assert.ok(!globals.includes('width: calc(100% + 2.8rem) !important;'), 'Subtask rows should not use guessed width compensation for action alignment.');
assert.ok(!globals.includes('margin-left: -2.8rem !important;'), 'Subtask rows should not use guessed negative margins for action alignment.');
assert.ok(globals.includes('width: calc(var(--task-review-action-width) + var(--task-delete-action-width) + var(--task-action-gap)) !important;'), 'Main action layer should have a final fixed action-grid width.');
assert.ok(globals.includes('width: calc(var(--task-review-action-width) + var(--task-delete-action-width) + var(--task-action-gap)) !important;'), 'Subtask action layer should use the same fixed action-grid width as main tasks.');
assert.ok(globals.includes('position: absolute !important;\n  right: var(--task-action-right) !important;'), 'Subtask action layer should use the same absolute right alignment model as main tasks.');
assert.ok(globals.includes('.task-subtask-review-zone,\n.task-subtask-delete-zone {\n  height: 100% !important;'), 'Subtask action slots should span row height for visual centering.');
assert.ok(globals.includes('place-items: center !important;'), 'Subtask action slots/buttons should use place-items center.');
assert.ok(globals.includes('line-height: 0 !important;'), 'Subtask buttons should remove text line-box offset that visually lowers SVG icons.');
assert.ok(globals.includes('padding: 0 !important;'), 'Subtask buttons should not have padding that shifts icons.');
assert.ok(globals.includes('.task-subtask-review svg,\n.task-subtask-delete svg {\n  display: block !important;'), 'Subtask action SVGs should be block-level to avoid baseline offset.');
assert.ok(globals.includes('.task-subtask-row {') && globals.includes('grid-template-columns:'), 'Subtask row should use grid layout.');
assert.ok(watercolor.includes('.theme-watercolor .task-icon-action'), 'Watercolor should explicitly use compact shared action button size.');
assert.ok(!watercolor.includes('width: 2.8rem') && !watercolor.includes('height: 2.8rem'), 'Watercolor should not keep oversized action buttons.');

console.log('verify-task-action-alignment passed');
