import type { ComponentProps } from 'react';
import { AppMainContent } from '../components/AppMainContent';
import { AppOverlayStack } from '../components/AppOverlayStack';
import { TitleBar } from '../components/TitleBar';
import { createAppShellOverlayComposition } from './appShellOverlayComposition';
import { createAppShellMainContentComposition } from './appShellMainContentComposition';
import type { AppShellCompositionOptions } from './appShellCompositionTypes';

export type { AppShellCompositionOptions } from './appShellCompositionTypes';

export interface AppShellComposition {
  titleBarProps: ComponentProps<typeof TitleBar>;
  overlayStackProps: ComponentProps<typeof AppOverlayStack>;
  mainContentProps: ComponentProps<typeof AppMainContent>;
}

export function createAppShellComposition({
  compactMode,
  settingsOpen,
  lockWindowPosition,
  appSettings,
  personalization,
  reviewDialogState,
  appUiActions,
  appModalActions,
  appPersonalizationActions,
  completionActions,
  mainScrollRef,
  isDark,
  selectedDate,
  allDates,
  setSelectedDate,
  allTasks,
  calendarTasks,
  editTaskReview,
  deleteTaskReview,
  totalCount,
  completedCount,
  obsidianPath,
  syncStatus,
  chooseObsidianFolder,
  openSelectedDailyNote,
  selectedDateTasksForCommands,
  dailyWork,
  dailyInspiration,
  hasDailyWorkContent,
  hasDailyInspirationContent,
  isDailyWorkOpen,
  isInspirationOpen,
  updateDailyWork,
  updateDailyInspiration,
  activeTab,
  setActiveTab,
  visibleTasks,
  sourceOrderForSelectedDate,
  dragDisabled,
  reorderSourceGroups,
  reorderTasksWithinSource,
  searchQuery,
  setSearchQuery,
  searchOpen,
  showOpenOnly,
  priorityFilter,
  setPriorityFilter,
  deleteTask,
  editTask,
  deleteSubtask,
  toggleTaskCollapse,
  changePriority,
  editRequest,
  addTask,
  companionOpen,
  companionSettings,
  companionPlan,
  companionStatus,
  updateCompanionSettings,
  chooseCompanionVault,
  previewCompanion,
  syncCompanion,
  importCompanionMobileInbox,
  obsidianTemplates,
  settingsSyncPreview,
  clearCompleted,
  updateAppSettings,
  updateObsidianTemplates,
  previewSettingsSync,
  resetObsidianTemplates,
  aiOnboarding,
  editingTemplateKind,
}: AppShellCompositionOptions): AppShellComposition {
  const titleBarProps = {
    compactMode,
    settingsOpen,
    lockWindowPosition,
    language: appSettings.language,
    onToggleCompactMode: appModalActions.toggleCompactMode,
    onToggleSettings: appModalActions.toggleSettings,
    onToggleLockWindowPosition: appModalActions.toggleLockWindowPosition,
  };
  const mainContentProps = createAppShellMainContentComposition({
    appSettings,
    appUiActions,
    completionActions,
    mainScrollRef,
    isDark,
    selectedDate,
    allDates,
    setSelectedDate,
    calendarTasks,
    allTasks,
    editTaskReview,
    deleteTaskReview,
    totalCount,
    completedCount,
    obsidianPath,
    syncStatus,
    chooseObsidianFolder,
    openSelectedDailyNote,
    selectedDateTasksForCommands,
    dailyWork,
    dailyInspiration,
    hasDailyWorkContent,
    hasDailyInspirationContent,
    isDailyWorkOpen,
    isInspirationOpen,
    updateDailyWork,
    updateDailyInspiration,
    activeTab,
    setActiveTab,
    visibleTasks,
    sourceOrderForSelectedDate,
    dragDisabled,
    reorderSourceGroups,
    reorderTasksWithinSource,
    searchQuery,
    setSearchQuery,
    searchOpen,
    showOpenOnly,
    priorityFilter,
    setPriorityFilter,
    deleteTask,
    editTask,
    deleteSubtask,
    toggleTaskCollapse,
    changePriority,
    editRequest,
    addTask,
    toggleDarkModeAction: appPersonalizationActions.toggleDarkModeAction,
  });
  const overlayStackProps = createAppShellOverlayComposition({
    settingsOpen,
    personalization,
    appSettings,
    obsidianTemplates,
    obsidianPath,
    settingsSyncPreview,
    isDark,
    selectedDate,
    completedCount,
    allTasks,
    clearCompleted,
    appPersonalizationActions,
    updateAppSettings,
    updateObsidianTemplates,
    chooseObsidianFolder,
    previewSettingsSync,
    resetObsidianTemplates,
    appModalActions,
    companionOpen,
    companionSettings,
    companionPlan,
    companionStatus,
    updateCompanionSettings,
    chooseCompanionVault,
    previewCompanion,
    syncCompanion,
    importCompanionMobileInbox,
    reviewDialogState,
    completionActions,
    deleteTaskReview,
    aiOnboarding,
    editingTemplateKind,
  });

  return {
    titleBarProps,
    overlayStackProps,
    mainContentProps,
  };
}
