import type { ComponentProps } from 'react';
import type { AddTaskInput } from '../components/AddTaskInput';
import type { AppMainContent } from '../components/AppMainContent';
import type { AppTopContent } from '../components/AppTopContent';
import type { DateNavigator } from '../components/DateNavigator';
import type { Header } from '../components/Header';
import type { ReviewView } from '../components/ReviewView';
import type { TabBar } from '../components/TabBar';
import type { TaskList } from '../components/TaskList';
import type { TitleBar } from '../components/TitleBar';
import type { createAppUiActions } from './appUiActions';
import type { AppShellOverlayCompositionOptions } from './appShellOverlayComposition';

export interface AppShellCompositionOptions extends AppShellOverlayCompositionOptions {
  compactMode: ComponentProps<typeof TitleBar>['compactMode'];
  lockWindowPosition: ComponentProps<typeof TitleBar>['lockWindowPosition'];
  appUiActions: ReturnType<typeof createAppUiActions>;
  mainScrollRef: ComponentProps<typeof AppMainContent>['mainScrollRef'];
  allDates: ComponentProps<typeof DateNavigator>['allDates'];
  setSelectedDate: ComponentProps<typeof DateNavigator>['onDateChange'];
  calendarTasks: ComponentProps<typeof DateNavigator>['tasks'];
  editTaskReview: ComponentProps<typeof ReviewView>['onEditReview'];
  totalCount: ComponentProps<typeof Header>['totalCount'];
  syncStatus: ComponentProps<typeof Header>['syncStatus'];
  openSelectedDailyNote: ComponentProps<typeof Header>['onOpenTodayNote'];
  selectedDateTasksForCommands: ComponentProps<typeof AppTopContent>['selectedDateTasksForCommands'];
  dailyWork: ComponentProps<typeof AppTopContent>['dailyWork'];
  dailyInspiration: ComponentProps<typeof AppTopContent>['dailyInspiration'];
  hasDailyWorkContent: ComponentProps<typeof AppTopContent>['hasDailyWorkContent'];
  hasDailyInspirationContent: ComponentProps<typeof AppTopContent>['hasDailyInspirationContent'];
  isDailyWorkOpen: ComponentProps<typeof AppTopContent>['isDailyWorkOpen'];
  isInspirationOpen: ComponentProps<typeof AppTopContent>['isInspirationOpen'];
  updateDailyWork: ComponentProps<typeof AppTopContent>['onChangeDailyWork'];
  updateDailyInspiration: ComponentProps<typeof AppTopContent>['onChangeDailyInspiration'];
  activeTab: ComponentProps<typeof TabBar>['activeTab'];
  setActiveTab: ComponentProps<typeof TabBar>['onTabChange'];
  visibleTasks: ComponentProps<typeof TaskList>['tasks'];
  sourceOrderForSelectedDate: ComponentProps<typeof TaskList>['sourceOrder'];
  dragDisabled: ComponentProps<typeof TaskList>['dragDisabled'];
  reorderSourceGroups: ComponentProps<typeof TaskList>['onReorderSources'];
  reorderTasksWithinSource: ComponentProps<typeof TaskList>['onReorderTasks'];
  searchQuery: ComponentProps<typeof TaskList>['searchQuery'];
  setSearchQuery: ComponentProps<typeof TaskList>['onSearchChange'];
  searchOpen: ComponentProps<typeof TaskList>['searchOpen'];
  showOpenOnly: ComponentProps<typeof TaskList>['showOpenOnly'];
  priorityFilter: ComponentProps<typeof TaskList>['priorityFilter'];
  setPriorityFilter: ComponentProps<typeof TaskList>['onPriorityFilterChange'];
  deleteTask: ComponentProps<typeof TaskList>['onDelete'];
  editTask: ComponentProps<typeof TaskList>['onEdit'];
  deleteSubtask: ComponentProps<typeof TaskList>['onDeleteSubtask'];
  toggleTaskCollapse: ComponentProps<typeof TaskList>['onToggleCollapse'];
  changePriority: ComponentProps<typeof TaskList>['onPriorityChange'];
  editRequest: ComponentProps<typeof TaskList>['editRequest'];
  addTask: ComponentProps<typeof AddTaskInput>['onAdd'];
}
